# -*- coding: utf-8 -*-
"""Tugas 2  part 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M4GNDr1CVn-NCuTRWEH69If3_ZnAq4bR
"""

import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import FunctionTransformer

df = pd.read_csv(r'd:\SEM 4\Diamond\diamonds.csv')

df.head(10)

df.info()

df.describe()

import matplotlib.pyplot as plt
import seaborn as sns

# only predictors, omit price!
predictor_cols = ['carat', 'depth', 'table', 'x', 'y', 'z']

# visualise them if you like
plt.figure(figsize=(15,10))
for i, col in enumerate(predictor_cols):
    plt.subplot(2,3,i+1)
    sns.boxplot(y=df[col])
    plt.title(f'Boxplot of {col}')

# remove outliers column‑wise – price is not included
df_cleaned = df.copy()
for col in predictor_cols:
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1
    lb, ub = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    df_cleaned = df_cleaned[(df_cleaned[col] >= lb) &
                            (df_cleaned[col] <= ub)]

print(df.shape, '→', df_cleaned.shape, 'after outlier removal')

df_cleaned.head()

# after cleaning we will need these lists again; price is not a predictor here
numerical_cols = ['carat', 'depth', 'table', 'x', 'y', 'z', 'price']
categorical_cols = ['cut', 'color', 'clarity']

plt.figure(figsize=(8,6))
sns.countplot(y='cut', hue='cut', data=df_cleaned, order=df_cleaned['cut'].value_counts().index ,palette='plasma', legend=False)
plt.title('Distribution of Cut')
plt.xlabel('Count')
plt.ylabel('Cut')
plt.show()

plt.figure(figsize=(8,6))
sns.countplot(y='color', hue='color', data=df_cleaned, order=df_cleaned['color'].value_counts().index ,palette='plasma', legend=False)
plt.title('Distribution of Color')
plt.xlabel('Count')
plt.ylabel('Color')
plt.show()

plt.figure(figsize=(8,6))
sns.countplot(y='clarity', hue='clarity', data=df_cleaned, order=df_cleaned['clarity'].value_counts().index ,palette='plasma', legend=False)
plt.title('Distribution of Clarity')
plt.xlabel('Count')
plt.ylabel('Clarity')
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df_cleaned['carat'], kde=True)
plt.title('Distribution of Carat')
plt.xlabel('Carat')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df_cleaned['depth'], kde=True)
plt.title('Distribution of Depth')
plt.xlabel('Depth')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df_cleaned['table'], kde=True)
plt.title('Distribution of Table')
plt.xlabel('Table')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df_cleaned['price'], kde=True)
plt.title('Distribution of Price')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df_cleaned['x'], kde=True)
plt.title('Distribution of x')
plt.xlabel('X')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df_cleaned['y'], kde=True)
plt.title('Distribution of Y')
plt.xlabel('Y')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df_cleaned['z'], kde=True)
plt.title('Distribution of Z')
plt.xlabel('Z')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(18, 6))

avg_price_cut = df_cleaned.groupby('cut')['price'].mean().sort_values(ascending=False).reset_index()
plt.subplot(1, 3, 1)
sns.barplot(x='cut', y='price', hue='cut', data=avg_price_cut, palette='viridis', legend=False)
plt.title('Average Price by Cut')
plt.xlabel('Cut')
plt.ylabel('Average Price')

avg_price_color = df_cleaned.groupby('color')['price'].mean().sort_values(ascending=False).reset_index()
plt.subplot(1, 3, 2)
sns.barplot(x='color', y='price',hue='color', data=avg_price_color, palette='viridis', legend=False)
plt.title('Average Price by Color')
plt.xlabel('Color')
plt.ylabel('Average Color')

avg_price_clarity = df_cleaned.groupby('clarity')['price'].mean().sort_values(ascending=False).reset_index()
plt.subplot(1, 3, 3)
sns.barplot(x='clarity', y='price', hue='clarity', data=avg_price_clarity, palette='viridis', legend=False)
plt.title('Average Price by Clarity')
plt.xlabel('Clarity')
plt.ylabel('Average Price')

plt.tight_layout()
plt.show()

numerical_cols = [c for c in df_cleaned.select_dtypes(include=['float64', 'int64']).columns if c != 'price']

numerical_cols.append('price')

corr_matrix = df_cleaned[numerical_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='RdBu',
    fmt='.2f',
    linewidths=0.5,
)
plt.title('Correlation Matrix')
plt.show()

cat_cols = ['cut','color','clarity']
cat_ord = ColumnTransformer(
    [('ord', OrdinalEncoder(
         categories=[['Fair','Good','Very Good','Premium','Ideal'],
                     ['J','I','H','G','F','E','D'],
                     ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']]),
      cat_cols)],
    remainder='passthrough'
)

pipeline = Pipeline([
    ('clean', FunctionTransformer(clean_outliers)),  # user‑defined fn
    ('encode', cat_ord),
    ('model', RandomForestRegressor(random_state=42))
])

pipeline.fit(X_train, y_train)